name: clothes_app
description: A new Flutter project.


publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.11.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  firebase_core: 0.3.4
  firebase_auth: 0.8.4+4
  cloud_firestore: 0.9.13+1
#  firebase_core: ^1.12.0
#  firebase_auth: ^3.3.6
#  cloud_firestore: ^3.1.7
  provider: ^6.0.2
  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - icons/
